### ISSUE TITLE
Force portal mode from application

### ISSUE THREAD

**Issue by balucio** [khoih-prog/Blynk_Async_WM#2]
Hi, how I can force entering in portal mode from application?

Thank you.

**Comment by khoih-prog** [comment]
Currently, **the library doesn't provide a direct way to force entering the Config Portal (CP) from application**, as this is over-complicated and not necessary for all use cases. I just prefer the simpler approach, yet the users can add / merge more features with other libraries.

But definitely, I'll consider add the optional feature if there are **more enhancement requests** for this, just not sure about the time frame.

In the mean time, you can use one of these temporary solutions

1. Create a Blynk virtual button, then use it to trigger the CP by reading the flag in the loop(). Check these examples for a way to do
  - [**ConfigOnSwitch of ESP_WiFiManager**](https://github.com/khoih-prog/ESP_WiFiManager/tree/master/examples/ConfigOnSwitch)
  - [**Async_ConfigOnSwitch of ESPAsync_WiFiManager**](https://github.com/khoih-prog/ESPAsync_WiFiManager/tree/master/examples/Async_ConfigOnSwitch)

2. Create a Blynk virtual button, then use it to trigger DoubleReset or MultiReset within predetermined time. 
  - Button => `ESP32 ESP.restart();` or `ESP8266 ESP.reset();`
  - The [**Async_ESP32WM_Config example**](https://github.com/khoih-prog/Blynk_Async_WM/tree/master/examples/Async_ESP32WM_Config) can be used to detect such as DoubleReset.

Good Luck,

**Comment by khoih-prog** [comment]
### Update

The requested feature has been available from v1.2.1

---

### Releases v1.2.1

1. Add functions to control Config Portal from software or Virtual Switches. Check [How to trigger a Config Portal from code #25](https://github.com/khoih-prog/Blynk_WM/issues/25)
2. Add examples to demo the new Virtual ConfigPortal SW feature
3. Optimize code
