### ISSUE TITLE
On ESP01-S 1M Serial does not working

### ISSUE THREAD

**Issue by balucio** [khoih-prog/Blynk_Async_WM#3]
Hi,
currenly I testing your great library on an ESP-01S.
I initialize the serial interface at begin of  `setup()`, the I call the `setupPortal` function to configure the `Blynk_Async_WM` library with default parameters. After the setup the serial interface does not work anymore, i.e. `Serial.print` does not print anything.
Please note that same code works perfectly on other ESP Boards as the Wemos D1 mini.

```
void setup() {
  Serial.begin(APP_SERIAL_SPEED);
   while (!Serial);
   Serial.println("Inizio Setup");

   setupPortal();

  // From here the Serial does not work
 ...
}

void setupPortal() {
  
  // Setup WLAN and Blynk
    Serial.println("Setup portal");

  String config_portal_pass(HOSTNAME);
  String config_portal_ssid(HOSTNAME);

  Blynk.setConfigPortal( config_portal_ssid, config_portal_pass);
  Blynk.setConfigPortalIP ( IPAddress ( CONFIG_PORTAL_IPADDRESS ) );
  Blynk.setConfigPortalChannel(0);
  Blynk.begin(Blynk.getBoardName().c_str()); // DHCP (router) device name
  WiFi.hostname(Blynk.getBoardName());
}
```

In order to have the serial working again I need to reset It using:

```
    delay(500);
    Serial.end();
    Serial.begin(APP_SERIAL_SPEED);
    // Now Serial.print works...
```

**Comment by khoih-prog** [comment]
Thanks for sharing your experience which definitely will help other users.

The library is designed for full-fledged ESP8266, not for this ESP01(S) and it's good that you can apply into it. Just taking some precaution as the **Serial** is possibly used to control external devices (relays, etc.)
